### ISSUE TITLE
Getting an error during training the model

### ISSUE THREAD

**Issue by sdjavadi** [HKUST-KnowComp/MNE#11]
When I use the command "python3 train_model.py data/Vickers-Chan-7thGraders_multiplex.edges" I get this error. Would you help me solve the issue?

We are loading data from: data/Vickers-Chan-7thGraders_multiplex.edges
Finish loading data
Traceback (most recent call last):
  File "train_model.py", line 13, in <module>
    model = train_model(edge_data_by_type)
  File "../MNE/MNE.py", line 118, in train_model
    base_network = network_data['Base']
KeyError: 'Base'

**Comment by panda0881** [comment]
Hi, 

I have solved the problem. Basically, I just uncommented l.77 and l.78 of MNE.py. Please Check

Best Regards,
Hongming
