### ISSUE TITLE
Output files

### ISSUE THREAD

**Issue by sdjavadi** [HKUST-KnowComp/MNE#12]
I trained the model with its default dataset. However, it's not clear how to use the output. There are files named "tran_*.dat" , "addition_*.dat" and "base.dat". When I open them with a text editor, none of them is readable. It seems they are stored as a binary file. What steps should I take now?

**Comment by panda0881** [comment]
I just added a data loading function. You should be able to use it. If anything is not working, let me know.

PS: you can load the .dat file with numpy.fromfile()

**Comment by sdjavadi** [comment]
Can you give me an example/code how to get the embedding of a node _n_ located on relation _i_?
For example, I loaded the Add1.dat,Base.dat,Tran1.dat of the toy dataset with its default setting.  Their shapes are (145,), (2900,),(1000,) respectively. How could I get the embeddings of node 1 located on relation 1 for this example?

**Comment by panda0881** [comment]
Hi,

The Tran1.dat should be a matrix rather than a list of embeddings. you can
select the first row of Add1.dat and then multiply it with Tran1 and then
add the first row of Base.dat, which is exactly the Equation (1) in our
paper.

Best Regards,
Hongming

**Comment by sdjavadi** [comment]
By any chance is it possible to provide a code example that read and calculate equation 1 of your paper? It would be great to have a matrix for a relation that each row represent the final embedding space of a node on that relation. Sorry for bothering you again, but when I read the output files with "numpy.fromfile()" function I only get single long lists which clearly need to be reshaped to proper dimensions. I just wanted to make sure that I'm doing the right thing.

**Comment by panda0881** [comment]
Hi,

You can try to see if you can understand the load_model function in
L.163-180 of MNE.py file.

Best Regards,
Hongming

**Comment by sdjavadi** [comment]
Yes, I used the method to load the output files, but my problem is how to get the final embedding as it is described in Eq 1. 
out = load_model("MNE/model")
print(out['base'].shape )
print(out['tran']['1'].shape)
print(out['addition']['1'].shape)

(2900,)
(1000,)
(145,)

You said 

> select the first row of Add1.dat and then multiply it with Tran1 and then
add the first row of Base.dat, which is exactly the Equation (1) in our
paper.

but how could I select the first row of a single list !? Shouldn't be the 'base','tran' and 'out'  two-dimensional matrices instead of one-dimensional lists?

**Comment by panda0881** [comment]
Now I understand your problem. The reason is that np.tofile function will
merge the matrix into one single vector. I have fixed it by replacing
np.tofile/fromfile with np.save/load functions. Please check.

Best Regards,
Hongming

**Comment by sdjavadi** [comment]
Traceback (most recent call last):
  File "train_model.py", line 14, in <module>
    model = train_model(edge_data_by_type)
  File "/home/saeed2/MNE/MNE.py", line 124, in train_model
    base_embedding, _, _, index2word = train_embedding(None, base_walks, 'Base', 100, 10, 1)
  File "/home/saeed2/MNE/MNE.py", line 112, in train_embedding
    new_model = MNE(training_data, size=200, window=5, min_count=0, sg=1, workers=4, iter=iter, small_size=info_size, initial_embedding=initial_embedding, base_weight=base_weight)
  File "/home/saeed2/MNE/MNE.py", line 387, in __init__
    self.train(sentences)
  File "/home/saeed2/MNE/MNE.py", line 680, in train
  File "/usr/lib/python3.4/warnings.py", line 18, in showwarning
    file.write(formatwarning(message, category, filename, lineno, line))
  File "/usr/lib/python3.4/warnings.py", line 26, in formatwarning
    line = linecache.getline(filename, lineno) if line is None else line
  File "/usr/lib/python3.4/linecache.py", line 15, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python3.4/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python3.4/linecache.py", line 127, in updatecache
    lines = fp.readlines()
  File "/usr/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 399: invalid start byte

Getting this error from running the latest version.

**Comment by panda0881** [comment]
That error didn't occur on my laptop. it seems like a decoding error.

Firstly, you need to make sure the training data in encoded with 'utf-8'.
And then you can try to change l.68 of MNE.py to  with open(f_name, 'r',
'utf-8') as f:

If it still doesn't work, try to use other decoding methods like ascii.

This is not a general bug, it depends on the machine you use.

**Comment by sdjavadi** [comment]
I tried different codecs, no success. I don't think that causes the problem. What happened to your previous file reading function? why don't you use the read_csv function from Panda library?
