### ISSUE TITLE
main.py: error: unrecognized arguments: data/Vickers-Chan-7thGraders_multiplex.edges

### ISSUE THREAD

**Issue by lxzmxl** [HKUST-KnowComp/MNE#13]
when I run the demo python3 main.py data/Vickers-Chan-7thGraders_multiplex.edges as recommended, this error occurs. I think it's because the command line arguments not including the dataset.

**Comment by panda0881** [comment]
Hi,

Can you show me the error message?

Best Regards,
Hongming

**Comment by lxzmxl** [comment]
now there is another question。
![1](https://user-images.githubusercontent.com/24810695/46197203-ae539480-c33b-11e8-9a47-74a4e8eb4402.png)

**Comment by panda0881** [comment]
That is because you are using network 2.0, while my code was written with network 1.12. You can either downgrade your package or slightly modify this sentence by yourself.
