### ISSUE TITLE
something about common embedding bn

### ISSUE THREAD

**Issue by MrLeeeee** [HKUST-KnowComp/MNE#14]
Hi, Hongming ZHANG.
First, I would like to say that it is very nice of you to share your code with the community.
And I have a question. In your paper, the common bn is changed layer by layer. However, in the code, the bn is generated by all the walks before training for Xn and Un. Would it spends too much time?

**Comment by panda0881** [comment]
In my experiment, It will cost slightly more time, but won't be too much. You can try to remove that part and test the execution time.
