### ISSUE TITLE
Error demo with main.py

### ISSUE THREAD

**Issue by LPioL** [HKUST-KnowComp/MNE#16]
Hello, I have an erro while trying to use the demo command:
 
Input:  python3 main.py data/Vickers-Chan-7thGraders_multiplex.edges
Output; usage: main.py [-h] [--input [INPUT]] [--output [OUTPUT]]
               [--dimensions DIMENSIONS] [--walk-length WALK_LENGTH]
               [--num-walks NUM_WALKS] [--window-size WINDOW_SIZE]
               [--iter ITER] [--workers WORKERS] [--p P] [--q Q] [--weighted]
               [--unweighted] [--directed] [--undirected]
main.py: error: unrecognized arguments: data/Vickers-Chan-7thGraders_multiplex.edges

**Comment by panda0881** [comment]
Hi,

I didn't have this error. Maybe your package version is different from
mine.

Anyway, you can try comment l.412 and uncomment l.413 and then run our demo
with python3 main.py

Best Regards,
Hongming

**Comment by LPioL** [comment]
Thanks for the answer.
