### ISSUE TITLE
Error with big multiplex network

### ISSUE THREAD

**Issue by LPioL** [HKUST-KnowComp/MNE#19]
Hi, 
I applied your method on bigger network like for example Drosophila_Multiplex_Genetic, 7 layers Multiplex, Nodes: 8215, Edges: 43366, from https://comunelab.fbk.eu/data.php.

I have this error with your parameters:
`ValueError: Input contains NaN, infinity or a value too large for dtype('float32').`

I reduced the iter parameter to 10 but it is still the same. Any idea ?

Best.

**Comment by panda0881** [comment]
Hi,

This is probably because your network is very dense. One thing you can try is decreasing the parameter r, which is the `limitation' in l.243 of MNE.py

Best Regards,
Hongming
