### ISSUE TITLE
may you help understand how it is better than other approaches

### ISSUE THREAD

**Issue by Sandy4321** [HKUST-KnowComp/MNE#2]
VERSE: https://arxiv.org/abs/1803.04742
https://github.com/xgfs/verse
and

node2vec: Scalable Feature Learning for Networks.

https://snap.stanford.edu/node2vec/
https://github.com/eliorc/Medium/blob/master/Nod2Vec-FIFA17-Example.ipynb
https://towardsdatascience.com/node2vec-embeddings-for-graph-data-32a866340fef
https://github.com/aditya-grover/node2vec
plain python code
https://github.com/eliorc/node2vec

**Comment by panda0881** [comment]
As you may know, the node2vec is designed for the single-layer network but our model is designed for multiplex network, which means that there could be multiple relation types between nodes. 
You can read our paper:
http://www.cse.ust.hk/~yqsong/papers/2018-IJCAI-MultiplexNetworkEmbedding.pdf
for further details.

Best Regards,
Hongming

**Comment by Sandy4321** [comment]
great thanks for help
