### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by 960924** [HKUST-KnowComp/MNE#22]
I recompile line.cpp，then ./line..  ,but I get an "Segmentation fault (core dumped)" error。
And when I run main.py, I get an "TypeError: object of type 'dict_keyiterator' has no len()" error.

**Comment by panda0881** [comment]
For the first question, you should refer to LINE's original repo (https://github.com/tangjianpku/LINE)

For the second one, please check the package versions.
