### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float32')

### ISSUE THREAD

**Issue by dandan0502** [HKUST-KnowComp/MNE#6]
######     Thanks greatly for your job! I ran your code with the given dataset successfully but encountered a problem with my own datasets.
- ######  The format of my datasets is:

layer | head | tail
---|---|---
l1 | n1 | n2
l2 | n2 | n3
...|

######     There are two datasets(two layers multiplex networks). One has 609 nodes and 6604 edges(including two layers), and the other has 892 nodes and 21704 edges. I ran the codes with them and got the same error just shown in title. So I want to know whether my datasets is too large for my computer or other problems of my experience.
- ######     The configuration of my computer is:
        Memory 7.7GiB
        Process Intel® Core™ i7-4790 CPU @ 3.60GHz × 8 
        OS type 64-bit
        Disk 115.8GB

**Comment by panda0881** [comment]
Hi,

I'm guessing the error is because some of the data in your dataset is missing or the format of your dataset is not as same as mine. You can check line 60-80 of MNE.py and modify it based on your format.

If you still have any problem, you are welcome to share the full error message (which line it reports the error) and the sample of your dataset.

Best Regards,
Hongming

**Comment by dandan0502** [comment]
###### Great thanks for soon answer!

###### I checked my datasets' format and the error message, and there is a overflow of data(this is a screenshot on another computer, don't mind):

![image](https://github.com/wapleeeeee/Ant_algorithm/blob/master/ans/123.jpg?raw=true)

###### The weights range of one network is 0 ~ 2000 and the other is 0 ~ 477. Are they too large ?

**Comment by panda0881** [comment]
Hi,

As I was using the small dataset, I set the default training iteration to be 100, If you are using the large dataset, you can try to reduce the training iteration to 10 without influencing the performance and that should solve your problem. (Actually, that is one hyper-parameter you can tune, but my experience as long as it is larger than one threshold, the performance will be stable)

You may want to check line 116 of "MNE.py"

Hongming

**Comment by dandan0502** [comment]
###### Hi Hongming,
###### &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;    Thank you a lot for your generous help. My problem has been solved!  
###### Best wishes,
###### Mia
