### ISSUE TITLE
Training the model is taking too much time.

### ISSUE THREAD

**Issue by parul-gupta29** [HKUST-KnowComp/MNE#7]
Hi,
I'm trying to run the code with 2 layers and 13224 number of nodes.  It's been more than 12 hours and the train_model.py script is still running.
Am I using too large a dataset or am I missing out on something?
Can you please help.

**Comment by panda0881** [comment]
As we are using Numpy to train the model, the speed could be relatively small for large networks. We will soon release a tensorflow version, which is much faster.

Hongming
