### ISSUE TITLE
Which vector do you use for node classification?

### ISSUE THREAD

**Issue by Yujun-Yan** [HKUST-KnowComp/MNE#8]
Hi, Hongming. I am wondering which vector do you use for node classification? Every node has a series of vectors, how can we get a unified vector for each node?

**Comment by panda0881** [comment]
It depends on your network. In our experiment, we simply take the average of all these vectors. However, if you have any knowledge about these networks, like which one is more important, as shown in our paper, you can assign weight wi to different layers. Actually, the weight of different layers is a hyperparameter that you can tune based on your data.

Hongming
